const img = {
  myAvatar: new URL("./avatars/moi.png", import.meta.url).href,
  iconDev: new URL("./icons/icon-dev.svg", import.meta.url).href,
  iconApp: new URL("./icons/icon-app.svg", import.meta.url).href,
  blogImage1: new URL("./blog/blog-1.webp", import.meta.url).href,
  blogImage2: new URL("./blog/blog-2.webp", import.meta.url).href,
  blogImage3: new URL("./blog/blog-3.webp", import.meta.url).href,
  blogImage4: new URL("./blog/blog-4.png", import.meta.url).href,
  blogImage5: new URL("./blog/blog-5.webp", import.meta.url).href,
  blogImage6: new URL("./blog/blog-6.webp", import.meta.url).href,
  blogImage7: new URL("./blog/blog-7.webp", import.meta.url).href,
  blogImage8: new URL("./blog/blog-8.png", import.meta.url).href,
  projectImage1: new URL("./projets/portfolio.png", import.meta.url).href,
  projectImage2: new URL("./projets/void.png", import.meta.url).href,
  projectImage3: new URL("./projets/gdef.png", import.meta.url).href,
  projectImage4: new URL("./projets/tgv.png", import.meta.url).href,
  avatarImage1: new URL("./avatars/avatar-1.png", import.meta.url).href,
  avatarImage2: new URL("./avatars/avatar-2.png", import.meta.url).href,
  avatarImage3: new URL("./avatars/avatar-3.png", import.meta.url).href,
  avatarImage4: new URL("./avatars/avatar-4.png", import.meta.url).href,
};
export default img;
